name: Portfolio CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          load: true
          tags: portfolio:production

      - name: Save Docker image
        run: |
          mkdir -p docker-image
          docker save portfolio:production > docker-image/portfolio.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: docker-image/portfolio.tar

  registry:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image from artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: docker-image

      - name: Log host and username
        run: |
          echo "Host: ${{ vars.HOST }}"
          echo "Username: ${{ vars.USERNAME }}"

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-image/portfolio.tar"
          target: "/home/root"

  deploy:
    needs: registry
    runs-on: ubuntu-latest
    steps:
      - name: Load and run Docker image on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker load < /home/root/docker-image/portfolio.tar
            docker rm -f portfolio || true
            docker run --name portfolio -d -p 3000:3000 portfolio:production